export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const LOGIN_USER = 'LOGIN_USER';
export const HANDLE_EMPLOYEE_FORM_UPDATE = 'HANDLE_EMPLOYEE_FORM_UPDATE';